# Run Tests then upload coverage to codecov.io
name: Run Tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run Tests and output Coverage
      run: yarn test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
